version: '3.8'

services:
  # Service 1: CSDL MySQL
  mysql-db:
    image: mysql:8.0
    container_name: DoAnTotNghiep-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DoAnTotNghiep
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Service 2: Backend Node.js
  backend:
    build: ./backend
    container_name: DoAnTotNghiep-Backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=DoAnTotNghiep
    depends_on:
      - mysql-db

volumes:
  mysql_data: