/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenDashboardRouteImport } from './routes/citizen/dashboard'
import { Route as OfficerDashboardRouteImport } from './routes/officer/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen/dashboard',
  path: '/citizen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/officer/dashboard',
  path: '/officer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/citizen/dashboard' | '/officer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/citizen/dashboard' | '/officer/dashboard'
  id: '__root__' | '/' | '/citizen/dashboard' | '/officer/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  OfficerDashboardRoute: typeof OfficerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/officer/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  OfficerDashboardRoute: OfficerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
