/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as CitizenIndexRouteImport } from './routes/citizen/index'
import { Route as CitizenDashboardRouteImport } from './routes/citizen/dashboard'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as OfficerCitizensRouteImport } from './routes/officer/citizens'
import { Route as OfficerDashboardRouteImport } from './routes/officer/dashboard'
import { Route as OfficerScanRouteImport } from './routes/officer/scan'
import { Route as OfficerVehiclesRouteImport } from './routes/officer/vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerCitizensRoute = OfficerCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerScanRoute = OfficerScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerVehiclesRoute = OfficerVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => OfficerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/citizens': typeof OfficerCitizensRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officer/vehicles': typeof OfficerVehiclesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/citizens': typeof OfficerCitizensRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officer/vehicles': typeof OfficerVehiclesRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/officer/citizens': typeof OfficerCitizensRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officer/vehicles': typeof OfficerVehiclesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/officer'
    | '/citizen/dashboard'
    | '/officer/citizens'
    | '/officer/dashboard'
    | '/officer/scan'
    | '/officer/vehicles'
    | '/citizen/'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen/dashboard'
    | '/officer/citizens'
    | '/officer/dashboard'
    | '/officer/scan'
    | '/officer/vehicles'
    | '/citizen'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/officer'
    | '/citizen/dashboard'
    | '/officer/citizens'
    | '/officer/dashboard'
    | '/officer/scan'
    | '/officer/vehicles'
    | '/citizen/'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/citizens': {
      id: '/officer/citizens'
      path: '/citizens'
      fullPath: '/officer/citizens'
      preLoaderRoute: typeof OfficerCitizensRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/scan': {
      id: '/officer/scan'
      path: '/scan'
      fullPath: '/officer/scan'
      preLoaderRoute: typeof OfficerScanRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/vehicles': {
      id: '/officer/vehicles'
      path: '/vehicles'
      fullPath: '/officer/vehicles'
      preLoaderRoute: typeof OfficerVehiclesRouteImport
      parentRoute: typeof OfficerRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface OfficerRouteChildren {
  OfficerCitizensRoute: typeof OfficerCitizensRoute
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerScanRoute: typeof OfficerScanRoute
  OfficerVehiclesRoute: typeof OfficerVehiclesRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerCitizensRoute: OfficerCitizensRoute,
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerScanRoute: OfficerScanRoute,
  OfficerVehiclesRoute: OfficerVehiclesRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
